In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('./defefcts.csv')
dataset

,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,returnQty,...,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty,defect
0,5,60,2,55,189,27,5,30,247,25,...,4,2,47,9,27,5,17,3,191,0
1,3,10,1,1,9,7,4,1,38,7,...,0,0,0,22,4,0,4,2,69,0
2,3,10,1,1,9,7,4,0,38,7,...,0,0,0,22,4,0,4,2,69,1
3,20,59,3,63,189,24,9,4,262,12,...,0,6,6,14,45,8,41,4,222,0
4,21,58,2,61,189,24,9,0,260,12,...,0,6,6,14,45,8,41,4,222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,52,124,12,144,963,110,9,0,804,20,...,0,0,26,16,32,4,30,6,689,1
6048,24,27,2,46,4,8,8,0,126,3,...,0,1,3,14,27,0,24,3,108,0
6049,22,27,1,46,4,8,8,0,126,3,...,0,1,3,14,27,0,24,3,108,1
6050,3,12,2,12,28,8,0,1,67,7,...,2,0,0,2,10,0,8,2,36,0
6051,5,11,1,11,21,7,0,0,62,6,...,2,0,0,1,9,0,7,2,37,1

# Описание признаков датасета

| Признак | Описание |
|---------|----------|
| `cbo` | Coupling Between Objects (связи между классами) |
| `wmc` | Weighted Methods per Class (суммарная сложность методов) |
| `dit` | Depth of Inheritance Tree (глубина наследования) |
| `rfc` | Response for a Class (количество вызываемых методов) |
| `lcom` | Lack of Cohesion of Methods (несвязанность методов) |
| `totalMethods` | Общее количество методов |
| `totalFields` | Общее количество полей |
| `nosi` | Number of Static Invocations (вызовы статических методов) |
| `loc` | Lines of Code (строк кода) |
| `returnQty` | Количество операторов `return` |
| `loopQty` | Количество циклов (`for`, `while`) |
| `comparisonsQty` | Количество сравнений (`if`, `case`) |
| `tryCatchQty` | Количество блоков `try-catch` |
| `parenthesizedExpsQty` | Количество выражений в скобках |
| `stringLiteralsQty` | Количество строковых литералов |
| `numbersQty` | Количество числовых литералов |
| `assignmentsQty` | Количество присваиваний |
| `mathOperationsQty` | Количество математических операций |
| `variablesQty` | Количество переменных |
| `maxNestedBlocks` | Максимальная вложенность блоков кода |
| `uniqueWordsQty` | Количество уникальных слов в коде |
| `defect` | Целевая переменная (1 — есть дефект, 0 — нет) |

Категориальных данных, неунитарно кодированных, нет, поэтому дополнительного кодирования производить не нужно

## Первое впечатление

1. Не совсем понятно, как производилась оценка сложности методов
2. Строки кода включают в себя информацию обо всех признаках и при этом не показывают какую-то характерную черту ПО

In [3]:
dataset.isnull().sum()

cbo                     0
wmc                     0
dit                     0
rfc                     0
lcom                    0
totalMethods            0
totalFields             0
nosi                    0
loc                     0
returnQty               0
loopQty                 0
comparisonsQty          0
tryCatchQty             0
parenthesizedExpsQty    0
stringLiteralsQty       0
numbersQty              0
assignmentsQty          0
mathOperationsQty       0
variablesQty            0
maxNestedBlocks         0
uniqueWordsQty          0
defect                  0
dtype: int64

Пустых значений нет, значит в этом плане предобработка не требуется

In [4]:
dataset.describe()

,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,returnQty,...,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty,defect
count,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,...,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000,6052.000000
mean,27.493721,86.177958,4.599141,68.954395,1242.030238,33.497852,14.049405,5.945142,442.074190,25.410112,...,3.218275,5.267845,36.727859,31.120621,65.899042,15.794118,49.700430,5.041143,219.283212,0.500000
std,33.214827,136.077153,9.288447,85.771623,9449.009245,53.556999,26.051029,25.263058,681.566084,47.058370,...,8.569417,13.956639,118.995663,85.715467,101.501174,40.011677,72.531059,5.920991,267.134701,0.500041
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000
25%,9.000000,18.000000,1.000000,18.000000,4.000000,8.000000,3.000000,0.000000,93.000000,4.000000,...,0.000000,0.000000,3.000000,2.000000,13.000000,1.000000,10.000000,2.000000,74.000000,0.000000
50%,18.000000,45.000000,2.000000,44.000000,43.000000,17.000000,7.000000,0.000000,230.000000,12.000000,...,1.000000,1.000000,12.000000,9.000000,34.000000,4.000000,27.000000,4.000000,139.000000,0.500000
75%,34.000000,100.000000,4.000000,89.000000,267.000000,39.000000,18.000000,3.000000,521.250000,28.000000,...,3.000000,5.000000,34.000000,29.000000,80.000000,14.000000,62.000000,6.000000,269.000000,1.000000
max,419.000000,1714.000000,285.000000,1203.000000,199855.000000,758.000000,903.000000,475.000000,8832.000000,579.000000,...,125.000000,218.000000,4566.000000,2856.000000,2016.000000,501.000000,1050.000000,77.000000,3345.000000,1.000000

Все признаки являются числовыми (некатегориальными)

In [ ]:
import seaborn as sns

In [ ]:
norm_target = (dataset
               .defect
               .value_counts(normalize=True)
               .mul(100)
               .rename('percent')
               .reset_index())
ax = sns.barplot(x='defect', y='percent', data=norm_target, palette=['black', 'orange'], hue='defect', legend=False)
for p in ax.patches:
    ax.annotate(
        f'{p.get_height()}%',
        (p.get_x() + p.get_width()/2.0, p.get_height()),
        ha='center',
        va='center',
        xytext=(0,4),
        textcoords='offset points'
    )

Посмотрим распределения признаков для ПО с наличием и отсутствием дефектов по отдельности

In [7]:
import matplotlib.pyplot as plt

In [ ]:
def draw_kde_feature_defects(feature, xlim=None):
    sns.displot(
        {
            'defect 0': dataset[dataset.defect==0][feature],
            'defect 1': dataset[dataset.defect==1][feature]
        },
        kind='kde',
        common_norm=True,
        palette=['black', 'orange']
    )
    plt.title(feature)
    plt.xlabel(feature)
    plt.ylabel('density')
    if xlim:
        plt.xlim(-50, xlim) 
    plt.show()

In [ ]:
for feature in dataset.columns.values[:-1]:
    draw_kde_feature_defects(feature)

In [ ]:
for feature in dataset.columns.values[:-1]:
    draw_kde_feature_defects(feature, 100)

Хоть сколько-то значимую информацию, возможно, несут только 4 признака: nosi, cbo, dit, rfc. Посмотрим их статистику

In [ ]:
def describe_feture_defects(feature, ds = dataset):
    print(feature)
    print(ds.groupby('defect')[feature].describe())
    print('\n')

In [ ]:
for feature in ['nosi', 'cbo', 'dit', 'rfc']:
    describe_feture_defects(feature)

In [ ]:
def mode_feature_defects(feature):
    print(dataset.groupby('defect')[feature].apply(lambda x: x.value_counts().index[0]))
    print('\n')

In [ ]:
for feature in ['nosi', 'cbo', 'dit', 'rfc']:
    mode_feature_defects(feature)

## Замечания
Вспомним:
| Признак | Описание |
|---------|----------|
| `nosi` | Number of Static Invocations (вызовы статических методов) |
| `cbo` | Coupling Between Objects (связи между классами) |
| `dit` | Depth of Inheritance Tree (глубина наследования) |
| `rfc` | Response for a Class (количество вызываемых методов) |

Получается:
1. Чем больше cbo, тем выше вероятность к дефекту
2. Характеристики dit говорят о том, что среднее дефектного ПО ниже, однако 50й процентиль одинаков, поэтому сложно что-то сказать о характерных отличиях экземляров, принадлежащих классам
3. Чем ниже rfc, тем выше вероятность к дефекту. Возможно, это связано с тем, что при малом количестве вызываемых методов происходит усложнение кода и алгоритмов в частости
4. Признак nosi самый интересный для данной задачи, ведь показывает явные маркеры принадлежности к тому или иному классу. То есть в среднем nosi выше у бездефектного ПО. Кроме того, 75й процентиль у дефектного ПО равен 0, поэтому не исключаю возможность бинаризировать nosi

In [ ]:
sns.heatmap(data=dataset[['nosi', 'cbo', 'dit', 'rfc']].corr(method='spearman'), fmt='.2f', annot=True, cmap='YlOrRd')

Видно, что cbo,dit и rfc коррелируют между собой, поэтому, например, для логистической регрессии можно объединить эти признаки в одну компоненту.

# Baseline Random Forest

In [5]:
from sklearn.model_selection import train_test_split

X, y = dataset.drop('defect', axis=1), dataset['defect']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, log_loss

In [ ]:
rfc = RandomForestClassifier(n_estimators=150, random_state=1)
rfc.fit(X_train, y_train)

In [ ]:
y_pred_rfc = rfc.predict(X_test)
y_pred_proba_rfc = rfc.predict_proba(X_test)
print(
    f'''ROC_AUC: {roc_auc_score(y_test, y_pred_proba_rfc[:, 1]):.3f}
Precision: {precision_score(y_test, y_pred_rfc):.3f}
Recall: {recall_score(y_test, y_pred_rfc):.3f}
F1: {f1_score(y_test, y_pred_rfc):.3f}
Logloss: {log_loss(y_test, y_pred_rfc):.3f}
''')

In [ ]:
metrics = pd.DataFrame(index=['roc-auc', 'precision', 'recall', 'f1', 'logloss'])
metrics['Baseline_RFC'] = [
    roc_auc_score(y_test, y_pred_proba_rfc[:, 1]),
    precision_score(y_test, y_pred_rfc),
    recall_score(y_test, y_pred_rfc),
    f1_score(y_test, y_pred_rfc),
    log_loss(y_test, y_pred_rfc)
]
metrics

In [8]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_rfc[:, 1])
roc_auc_rfc = auc(fpr, tpr)

plt.plot(fpr, tpr, color='orange', label=f'ROC curve (area={roc_auc_rfc:.3f})')
plt.plot([0, 1], [0, 1], color='black', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.legend()
plt.show()

# Random Forest на nosi и одной компоненте, включающей cbo, dit, rfc

In [9]:
significant_features = ['nosi', 'cbo', 'dit', 'rfc']

X_train_significant = X_train[significant_features]
X_test_significant = X_test[significant_features]

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [11]:
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.fit_transform(X_test)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_significant_std = sc.fit_transform(X_train_significant)
X_test_significant_std = sc.fit_transform(X_test_significant)

In [13]:
pca = PCA(n_components=1)
pc1_train = pca.fit_transform(X_train_significant_std[:, 1:])

In [14]:
import numpy as np

In [15]:
X_train_significant_pca = np.hstack((X_train_significant_std[:, 0].reshape(-1, 1), pc1_train))

In [16]:
rfc_significant_pca = RandomForestClassifier(n_estimators=150, random_state=1)

In [17]:
rfc_significant_pca.fit(X_train_significant_pca, y_train)

RandomForestClassifier(n_estimators=150, random_state=1)

In [ ]:
pc1_test = pca.transform(X_test_significant_std[:, 1:])
X_test_significant_pca = np.hstack((X_test_significant_std[:, 0].reshape(-1, 1), pc1_test))

In [ ]:
y_pred_rfc_significant_pca = rfc_significant_pca.predict(X_test_significant_pca)
y_pred_proba_rfc_significant_pca = rfc_significant_pca.predict_proba(X_test_significant_pca)

print(
    f'''ROC_AUC: {roc_auc_score(y_test, y_pred_proba_rfc_significant_pca[:, 1]):.3f}
Precision: {precision_score(y_test, y_pred_rfc_significant_pca):.3f}
Recall: {recall_score(y_test, y_pred_rfc_significant_pca):.3f}
F1: {f1_score(y_test, y_pred_rfc_significant_pca):.3f}
Logloss: {log_loss(y_test, y_pred_rfc_significant_pca):.3f}
''')

In [ ]:
metrics['RFC_PCA'] = [
    roc_auc_score(y_test, y_pred_proba_rfc_significant_pca[:, 1]),
    precision_score(y_test, y_pred_rfc_significant_pca),
    recall_score(y_test, y_pred_rfc_significant_pca),
    f1_score(y_test, y_pred_rfc_significant_pca),
    log_loss(y_test, y_pred_rfc_significant_pca)
]
metrics

# Random Forest на nosi, cbo, dit, rfc

In [18]:
rfc_significant = RandomForestClassifier(n_estimators=150, random_state=1)
rfc_significant.fit(X_train_significant, y_train)

RandomForestClassifier(n_estimators=150, random_state=1)

In [19]:
y_pred_rfc_significant = rfc_significant.predict(X_test_significant)
y_pred_proba_rfc_significant = rfc_significant.predict_proba(X_test_significant)

print(
    f'''ROC_AUC: {roc_auc_score(y_test, y_pred_proba_rfc_significant[:, 1]):.3f}
Precision: {precision_score(y_test, y_pred_rfc_significant):.3f}
Recall: {recall_score(y_test, y_pred_rfc_significant):.3f}
F1: {f1_score(y_test, y_pred_rfc_significant):.3f}
Logloss: {log_loss(y_test, y_pred_rfc_significant):.3f}
''')

ROC_AUC: 0.766
Precision: 0.717
Recall: 0.755
F1: 0.736
Logloss: 9.725

In [ ]:
metrics['RFC'] = [
    roc_auc_score(y_test, y_pred_proba_rfc_significant[:, 1]),
    precision_score(y_test, y_pred_rfc_significant),
    recall_score(y_test, y_pred_rfc_significant),
    f1_score(y_test, y_pred_rfc_significant),
    log_loss(y_test, y_pred_rfc_significant)
]
metrics

In [ ]:
plt.plot(fpr, tpr, color='black', label=f'ROC curve (area={roc_auc_rfc:.3f})')

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_rfc_significant[:, 1])
roc_auc_rfc = auc(fpr, tpr)
plt.plot(fpr, tpr, color='orange', label=f'ROC curve baseline (area={roc_auc_rfc:.3f})')

plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.legend()
plt.show()

# Random Forest подбор гиперпараметров по сетке с 4мя значимыми признаками

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
rfc_grid = RandomForestClassifier(random_state=1)

param_grid = {
    'n_estimators': [100, 150, 200, 300, 350, 500],
    'max_depth': [3, 5, 10, 20, 40],
    'min_samples_split': [2, 5, 10, 15]
}

grid_search = GridSearchCV(
    estimator=rfc_grid,
    param_grid=param_grid,
    cv=5,                    
    scoring='roc_auc',       
    n_jobs=-1,               
    verbose=1              
)

grid_search.fit(X_train_significant, y_train)

print("Лучшие параметры:", grid_search.best_params_)
print("Лучший результат:", grid_search.best_score_)

best_rfc_grid = grid_search.best_estimator_

Fitting 5 folds for each of 120 candidates, totalling 600 fits
Лучшие параметры: {'max_depth': 5, 'min_samples_split': 10, 'n_estimators': 200}
Лучший результат: 0.8354232647001684

In [24]:
y_pred_rfc_significant_grid = best_rfc_grid.predict(X_test_significant)
y_pred_proba_rfc_significant_grid = best_rfc_grid.predict_proba(X_test_significant)

print(
    f'''ROC_AUC: {roc_auc_score(y_test, y_pred_proba_rfc_significant_grid[:, 1]):.3f}
Precision: {precision_score(y_test, y_pred_rfc_significant_grid):.3f}
Recall: {recall_score(y_test, y_pred_rfc_significant_grid):.3f}
F1: {f1_score(y_test, y_pred_rfc_significant_grid):.3f}
Logloss: {log_loss(y_test, y_pred_rfc_significant_grid):.3f}
''')

ROC_AUC: 0.825
Precision: 0.758
Recall: 0.842
F1: 0.798
Logloss: 7.641

In [ ]:


metrics['RFC_GRID'] = [
    roc_auc_score(y_test, y_pred_proba_rfc_significant_grid[:, 1]),
    precision_score(y_test, y_pred_rfc_significant_grid),
    recall_score(y_test, y_pred_rfc_significant_grid),
    f1_score(y_test, y_pred_rfc_significant_grid),
    log_loss(y_test, y_pred_rfc_significant_grid)
]
metrics

In [ ]:
plt.plot(fpr, tpr, color='black', label=f'ROC curve (area={roc_auc_rfc:.3f})')

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_rfc_significant_grid[:, 1])
roc_auc_rfc = auc(fpr, tpr)
plt.plot(fpr, tpr, color='orange', label=f'ROC curve baseline (area={roc_auc_rfc:.3f})')

plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.legend()
plt.show()

# Baseline Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

In [ ]:
lrcv = LogisticRegressionCV(cv=5, scoring='roc_auc', random_state=1)
lrcv.fit(X_train_std, y_train)

In [ ]:
y_pred_lrcv = lrcv.predict(X_test_std)
y_pred_proba_lrcv = lrcv.predict_proba(X_test_std)

metrics['Baseline_LRCV'] = [
    roc_auc_score(y_test, y_pred_proba_lrcv[:, 1]),
    precision_score(y_test, y_pred_lrcv),
    recall_score(y_test, y_pred_lrcv),
    f1_score(y_test, y_pred_lrcv),
    log_loss(y_test, y_pred_lrcv)
]
metrics

# Logistic Regression на nosi и одной компоненте, включающей cbo, dit, rfc

In [ ]:
lrcv_pca = LogisticRegressionCV(cv=5, scoring='roc_auc', random_state=1)
lrcv_pca.fit(X_train_significant_pca, y_train)

In [ ]:
y_pred_lrcv_pca = lrcv_pca.predict(X_test_significant_pca)
y_pred_proba_lrcv_pca = lrcv_pca.predict_proba(X_test_significant_pca)

metrics['LRCV_PCA'] = [
    roc_auc_score(y_test, y_pred_proba_lrcv_pca[:, 1]),
    precision_score(y_test, y_pred_lrcv_pca),
    recall_score(y_test, y_pred_lrcv_pca),
    f1_score(y_test, y_pred_lrcv_pca),
    log_loss(y_test, y_pred_lrcv_pca)
]
metrics

# Logistic Regression на nosi, cbo, dit, rfc

In [ ]:
lrcv_significant = LogisticRegressionCV(cv=5, scoring='roc_auc', random_state=1)
lrcv_significant.fit(X_train_significant_std, y_train)

In [ ]:
y_pred_lrcv_significant = lrcv_significant.predict(X_test_significant_std)
y_pred_proba_lrcv_significant = lrcv_significant.predict_proba(X_test_significant_std)

metrics['LRCV'] = [
    roc_auc_score(y_test, y_pred_proba_lrcv_significant[:, 1]),
    precision_score(y_test, y_pred_lrcv_significant),
    recall_score(y_test, y_pred_lrcv_significant),
    f1_score(y_test, y_pred_lrcv_significant),
    log_loss(y_test, y_pred_lrcv_significant)
]
metrics

# Logistic Regression подбор гиперпараметров по сетке с 4мя значимыми признаками

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
param_grid = [
    {
        'solver': ['lbfgs'],
        'penalty': ['l2'],
        'C': [0.001, 0.01, 0.1, 1, 10, 100],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 300, 700, 1000]
    },
    {
        'solver': ['liblinear'],
        'penalty': ['l1', 'l2'],
        'C': [0.001, 0.01, 0.1, 1, 10, 100],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 300, 700, 1000]
    },
    {
        'solver': ['saga'],
        'penalty': ['l1', 'l2', 'elasticnet'],
        'C': [0.001, 0.01, 0.1, 1, 10, 100],
        'l1_ratio': [0.2, 0.5, 0.8],
        'class_weight': [None, 'balanced'],
        'max_iter': [100, 300, 700, 1000]
    }
]

lr_grid = LogisticRegression()
grid = GridSearchCV(
    lr_grid, 
    param_grid, 
    cv=5, 
    scoring='roc_auc', 
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train_significant_std, y_train)

print("\nЛучшие параметры:", grid.best_params_)
print(f"Лучший ROC-AUC: {grid.best_score_:.4f}")

best_lr_grid = grid.best_estimator_

In [ ]:
y_pred_lrcv_grid = best_lr_grid.predict(X_test_significant_std)
y_pred_proba_lrcv_grid = best_lr_grid.predict_proba(X_test_significant_std)

metrics['LRCV_GRID'] = [
    roc_auc_score(y_test, y_pred_proba_lrcv_grid[:, 1]),
    precision_score(y_test, y_pred_lrcv_grid),
    recall_score(y_test, y_pred_lrcv_grid),
    f1_score(y_test, y_pred_lrcv_grid),
    log_loss(y_test, y_pred_lrcv_grid)
]
metrics

# Baseline XGBClassifier

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
import xgboost

In [ ]:
xgb = xgboost.XGBClassifier(n_estimators=1000, max_depth=4, learning_rate=0.01)
xgb.fit(X_train_std, y_train)

In [ ]:
y_pred_xgb = xgb.predict(X_test_std)
y_pred_proba_xgb = xgb.predict_proba(X_test_std)

metrics['Baseline_XGB'] = [
    roc_auc_score(y_test, y_pred_proba_xgb[:, 1]),
    precision_score(y_test, y_pred_xgb),
    recall_score(y_test, y_pred_xgb),
    f1_score(y_test, y_pred_xgb),
    log_loss(y_test, y_pred_xgb)
]
metrics

# XGBClassifier randomized search на 4ёх парамтерах

In [ ]:
model = xgboost.XGBClassifier(random_state=1)

param_dist = {
    'n_estimators': randint(50, 500),      
    'max_depth': [3, 5, 7, 9, None],       
    'learning_rate': uniform(0.01, 0.3),   
    'subsample': uniform(0.5, 0.5)         
}

random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,   
    n_iter=100,                        
    cv=5,
    scoring='roc_auc',
    n_jobs=-1,
    random_state=2,
    verbose=1
)

random_search.fit(X_train_significant_std, y_train)

print("Лучшие параметры:", random_search.best_params_)
print("Лучший результат:", random_search.best_score_)

best_xgb = random_search.best_estimator_

In [ ]:
y_pred_xgb_grid = best_xgb.predict(X_test_significant_std)
y_pred_proba_xgb_grid = best_xgb.predict_proba(X_test_significant_std)

metrics['XGB_RandomizedSearch'] = [
    roc_auc_score(y_test, y_pred_proba_xgb_grid[:, 1]),
    precision_score(y_test, y_pred_xgb_grid),
    recall_score(y_test, y_pred_xgb_grid),
    f1_score(y_test, y_pred_xgb_grid),
    log_loss(y_test, y_pred_xgb_grid)
]
metrics

In [23]:
rfc_test = RandomForestClassifier(n_estimators=200, max_depth=5, min_samples_split=10, random_state=1)
rfc_test.fit(X_train, y_train)

y_pred_rfc_test = rfc_test.predict(X_test)
y_pred_proba_rfc_test = rfc_test.predict_proba(X_test)
print(
    f'''ROC_AUC: {roc_auc_score(y_test, y_pred_proba_rfc_test[:, 1]):.3f}
Precision: {precision_score(y_test, y_pred_rfc_test):.3f}
Recall: {recall_score(y_test, y_pred_rfc_test):.3f}
F1: {f1_score(y_test, y_pred_rfc_test):.3f}
Logloss: {log_loss(y_test, y_pred_rfc_test):.3f}
''')

ROC_AUC: 0.824
Precision: 0.759
Recall: 0.845
F1: 0.800
Logloss: 7.582